POST http://localhost:3001/api/notes
Content-Type: application/json

{
    "content": "testing backend",
    "important":true
}

###
DELETE http://localhost:3001/api/notes/4

###
GET http://localhost:3001/api/notes/